import { describe, it, expect, vi, beforeEach } from 'vitest'
import { auth } from '@/auth'
import { replaceDraft } from '@/lib/db/queries/drafts'
import { requireDraftOwner, ownershipErrorToResponse } from '@/lib/auth/require-owner'
import { getNarrativeByJob } from '@/lib/db/queries/narratives'
import { getVoiceSettings } from '@/lib/db/queries/voice'
import { generatePost } from '@/lib/ai/posts'
import { POST } from '@/app/api/drafts/[draftId]/replace/route'

vi.mock('@/auth', () => ({ auth: vi.fn() }))
vi.mock('@/lib/db/queries/drafts', () => ({
  replaceDraft: vi.fn(),
  updateDraftContent: vi.fn(),
  markDraftCopied: vi.fn(),
  getDraft: vi.fn(),
}))
vi.mock('@/lib/auth/require-owner', () => ({
  requireDraftOwner: vi.fn(),
  requireJobOwner: vi.fn(),
  requireRepoOwner: vi.fn(),
  ownershipErrorToResponse: vi.fn().mockReturnValue(null),
}))
vi.mock('@/lib/db/queries/narratives', () => ({ getNarrativeByJob: vi.fn() }))
vi.mock('@/lib/db/queries/voice', () => ({ getVoiceSettings: vi.fn() }))
vi.mock('@/lib/ai/posts', () => ({ generatePost: vi.fn() }))

const DRAFT_ID = 'draft-uuid-abcd'
const existingDraft = { id: DRAFT_ID, userId: 'user-1', jobId: 'job-uuid-1234', platform: 'linkedin' }
const replacedDraft = { id: DRAFT_ID, userId: 'user-1', platform: 'linkedin', content: 'Regenerated by Gemini', hashtags: ['#dev'] }
const narrativeRow = {
  id: 'n1', jobId: 'job-uuid-1234',
  story: 'A story', angle: 'Theme', targetAudience: '7',
  keyInsights: ['point one', 'point two'], suggestedHook: 'A',
}

const validBody = { platform: 'linkedin' as const, content: 'This is new LinkedIn content' }

function makeParams() {
  return { params: { draftId: DRAFT_ID } }
}

function makeRequest(body: unknown) {
  return new Request(`http://localhost/api/drafts/${DRAFT_ID}/replace`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
}

beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(ownershipErrorToResponse).mockReturnValue(null)
  vi.mocked(requireDraftOwner).mockResolvedValue(existingDraft as any)
  vi.mocked(replaceDraft).mockResolvedValue(replacedDraft as any)
  vi.mocked(getNarrativeByJob).mockResolvedValue(narrativeRow as any)
  vi.mocked(getVoiceSettings).mockResolvedValue({ tone: 'professional', technicalLevel: 7, audience: 'devs' } as any)
  vi.mocked(generatePost).mockResolvedValue({
    post: { content: 'Regenerated by Gemini', hashtags: ['#dev'] },
    _meta: { promptTokens: 10, completionTokens: 5, promptVersion: '1.0', rawOutput: '{}' },
  } as any)
})

describe('POST /api/drafts/[draftId]/replace', () => {
  it('returns 401 when not authenticated', async () => {
    vi.mocked(auth).mockResolvedValue(null as any)
    const res = await POST(makeRequest(validBody), makeParams())
    expect(res.status).toBe(401)
  })

  it('returns 400 for invalid platform', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    const res = await POST(makeRequest({ ...validBody, platform: 'instagram' }), makeParams())
    expect(res.status).toBe(400)
  })

  it('returns 400 for empty content', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    const res = await POST(makeRequest({ ...validBody, content: '' }), makeParams())
    expect(res.status).toBe(400)
  })

  it('returns 404 when narrative is missing', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    vi.mocked(getNarrativeByJob).mockResolvedValue(null as any)
    const res = await POST(makeRequest(validBody), makeParams())
    expect(res.status).toBe(404)
  })

  it('returns 201 with regenerated draft on success', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    const res = await POST(makeRequest(validBody), makeParams())
    expect(res.status).toBe(201)
    const data = await res.json()
    expect(data.draft).toBeTruthy()
  })

  it('calls generatePost with platform, narrative, voice', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    await POST(makeRequest(validBody), makeParams())
    expect(generatePost).toHaveBeenCalledWith(
      'linkedin',
      expect.objectContaining({ theme: 'Theme', story: 'A story', technicalDepth: 7 }),
      expect.objectContaining({ tone: 'professional' }),
    )
  })

  it('persists Gemini output, ignoring request content', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    await POST(makeRequest(validBody), makeParams())
    expect(replaceDraft).toHaveBeenCalledWith(
      DRAFT_ID,
      'job-uuid-1234',
      'user-1',
      expect.objectContaining({ platform: 'linkedin', content: 'Regenerated by Gemini', hashtags: ['#dev'] }),
    )
  })

  it('enforces draft ownership', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    await POST(makeRequest(validBody), makeParams())
    expect(requireDraftOwner).toHaveBeenCalledWith(DRAFT_ID, 'user-1')
  })

  it('accepts twitter platform', async () => {
    vi.mocked(auth).mockResolvedValue({ user: { id: 'user-1' } } as any)
    const res = await POST(makeRequest({ platform: 'twitter', content: 'Twitter content here' }), makeParams())
    expect(res.status).toBe(201)
    expect(generatePost).toHaveBeenCalledWith('twitter', expect.anything(), expect.anything())
  })
})
